name: build

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup SDK flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.16.9

      - name: Running flutter pub get
        run: flutter pub get

      - name: Build APK release
        run: flutter build apk --release

      - name: Upload artifact APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build WEB release
        run: flutter build web --release --web-renderer html

      - name: Upload artifact WEB
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web